
TYPE
	Step_typ : 
		(
		ROBOTCTRL_DISABLED,
		ROBOTCTRL_POWER,
		ROBOTCTRL_WAIT_POWER,
		ROBOTCTRL_HOME,
		ROBOTCTRL_WAIT_HOME,
		ROBOTCTRL_READY,
		ROBOTCTRL_CALCULATE,
		ROBOTCTRL_CHECK,
		ROBOTCTRL_CALCULATE_P1,
		ROBOTCTRL_CALCULATE_P2,
		ROBOTCTRL_IS_MOVE_NEEDED,
		ROBOTCTRL_MOVE,
		ROBOTCTRL_ERROR_WRONG_AIM,
		ROBOTCTRL_ERROR,
		ROBOTCTRL_STOP,
		ROBOTCTRL_INTERRUPT,
		ROBOTCTRL_INTERRUPTING,
		ROBOTCTRL_CONTINUE,
		ROBOTCTRL_POWER_OFF,
		ROBOTCTRL_COMPLITE
	);
END_TYPE